"""word candidates

Revision ID: 0e683cde1462
Revises: 96f9a975c80b
Create Date: 2026-06-19 18:09:45.523178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e683cde1462'
down_revision: Union[str, Sequence[str], None] = '96f9a975c80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('surface', sa.String(), nullable=False),
    sa.Column('lemma', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('snippet', sa.String(), nullable=True),
    sa.Column('theme_tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('surface')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_candidates')
    # ### end Alembic commands ###
