"""puzzles and entries

Revision ID: 7554bbffc1ee
Revises: 
Create Date: 2026-06-19 13:39:28.442347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7554bbffc1ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('live_date', sa.Date(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('grid_template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_puzzle_live_date_active', 'puzzles', ['live_date'], unique=True, postgresql_where=sa.text("status IN ('scheduled', 'published')"))
    op.create_table('entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('puzzle_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('clue', sa.String(), nullable=True),
    sa.Column('clue_status', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    op.drop_index('uq_puzzle_live_date_active', table_name='puzzles', postgresql_where=sa.text("status IN ('scheduled', 'published')"))
    op.drop_table('puzzles')
    # ### end Alembic commands ###
